# Generated by Django 4.1.7 on 2023-02-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('date_production_start', models.DateField()),
                ('date_production_stop', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('country_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('comment_text', models.TextField(max_length=5000)),
                ('car_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review_app.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='developer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review_app.developer'),
        ),
    ]
