# Generated by Django 4.1.7 on 2023-02-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='developer_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_app.developer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='car_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_app.car'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='country_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_app.country'),
        ),
    ]
